/**
 * Build script that inlines prompt files as TypeScript constants.
 *
 * This enables bundler compatibility by eliminating runtime fs.readFileSync calls.
 * The prompts become statically analyzable imports that bundlers can include.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const promptsDir = join(__dirname, "..", "..", "prompts");
const outputFile = join(__dirname, "..", "src", "generated-prompts.ts");

const collections = ["align_to_love"] as const;
const detailLevels = ["comprehensive", "standard", "concise", "terse"] as const;

// Ensure src directory exists
mkdirSync(dirname(outputFile), { recursive: true });

let output = `/**
 * Auto-generated file - DO NOT EDIT
 * Generated by scripts/generate-prompts.ts
 *
 * This file inlines prompt content at build time for bundler compatibility.
 */

export const PROMPTS = {
`;

for (const collection of collections) {
  output += `  "${collection}": {\n`;

  for (const level of detailLevels) {
    const promptPath = join(promptsDir, collection, `${level}.txt`);
    const content = readFileSync(promptPath, "utf-8");
    // Escape backticks and ${} for template literal safety
    const escaped = content.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
    output += `    "${level}": \`${escaped}\`,\n`;
  }

  output += `  },\n`;
}

output += `} as const;\n`;

writeFileSync(outputFile, output);
console.log("Generated prompts TypeScript file");
